#ifndef HEADER_DA_PRECOMPILARE_H_INCLUDED
#define HEADER_DA_PRECOMPILARE_H_INCLUDED

#ifndef WX_PRECOMPILED
#define WX_PRECOMPILED
#endif // WX_PRECOMPILED

#include "header_fisso.h"

#endif // HEADER_DA_PRECOMPILARE_H_INCLUDED
